import type { Plugin, ViteDevServer, ResolvedConfig } from 'vite'
import { createRequire } from 'module'
import { writeFileSync, existsSync } from 'fs'
import { resolve, dirname, relative } from 'path'
import { applyEnvOverrides, buildConfigScript } from '0config'
import type { RuntimeConfigInput, RuntimeConfigPluginOptions } from '0config'

const VIRTUAL_ID = 'virtual:runtime-config'
const RESOLVED_VIRTUAL_ID = '\0' + VIRTUAL_ID

// ─── helpers ────────────────────────────────────────────────────────────────

/**
 * Load a TS/JS config file at runtime using jiti (bundled) or plain require as
 * a fallback. Returns the default export.
 */
async function loadConfigFile(filePath: string): Promise<RuntimeConfigInput> {
  // Try jiti first (handles TypeScript natively)
  try {
    // Dynamic import so consumers don't need jiti unless they use config files
    const { createJiti } = await import('jiti')
    const jiti = createJiti(import.meta.url, { interopDefault: true })
    const mod = await jiti.import(filePath)
    return (mod as { default?: RuntimeConfigInput }).default ?? (mod as RuntimeConfigInput)
  } catch {
    // Fallback: plain require (works for pre-compiled JS configs)
    try {
      const _require = createRequire(import.meta.url)
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const mod = _require(filePath) as { default?: RuntimeConfigInput }
      return mod.default ?? (mod as unknown as RuntimeConfigInput)
    } catch (e) {
      throw new Error(
        `[runtime-config] Failed to load config file "${filePath}".\n` +
          `Install "jiti" to support TypeScript config files: pnpm add -D jiti\n` +
          String(e),
      )
    }
  }
}

/**
 * Generate a TypeScript module-augmentation file so that
 * useRuntimeConfig() is fully typed without manual declarations.
 */
function generateTypeFile(config: RuntimeConfigInput, configFilePath: string): void {
  const dir = dirname(configFilePath)
  const outPath = resolve(dir, 'runtime-config.d.ts')

  const privateKeys = Object.entries(config)
    .filter(([k]) => k !== 'public')
    .map(([k, v]) => `    ${k}: ${JSON.stringify(v) === 'null' ? 'null' : typeof v}`)
    .join('\n')

  const publicObj = (config.public ?? {}) as Record<string, unknown>
  const publicKeys = Object.entries(publicObj)
    .map(([k, v]) => `    ${k}: ${JSON.stringify(v) === 'null' ? 'null' : typeof v}`)
    .join('\n')

  const content = `// Auto-generated by @0config/vite — do not edit manually.
// Re-run your dev server or build to refresh this file.

declare module '0config' {
  interface PrivateRuntimeConfig {
${privateKeys}
  }

  interface PublicRuntimeConfig {
${publicKeys}
  }
}

declare module 'virtual:runtime-config' {
  import type { RuntimeConfig } from '0config'
  const config: RuntimeConfig
  export default config
}

export {}
`
  writeFileSync(outPath, content, 'utf-8')
  console.info(`[runtime-config] Types written to ${relative(process.cwd(), outPath)}`)
}

// ─── plugin ─────────────────────────────────────────────────────────────────

export function runtimeConfigPlugin(options: RuntimeConfigPluginOptions = {}): Plugin {
  const {
    configFile = './runtime.config.ts',
    envPrefix = 'RUNTIME_',
    generateTypes = false,
  } = options

  let resolvedViteConfig: ResolvedConfig
  let baseConfig: RuntimeConfigInput = {}
  let configFilePath: string | null = null
  let devServer: ViteDevServer | null = null

  async function loadAndApply(): Promise<RuntimeConfigInput> {
    if (configFilePath && existsSync(configFilePath)) {
      baseConfig = await loadConfigFile(configFilePath)
    }
    return applyEnvOverrides(baseConfig, process.env as Record<string, string | undefined>, envPrefix)
  }

  return {
    name: 'runtime-config',
    enforce: 'pre',

    // ── accept inline config passed directly into the plugin ──────────────
    config() {
      // Expose the env prefix as a define so client code can reference it
      return {
        define: {
          __RUNTIME_CONFIG_PREFIX__: JSON.stringify(envPrefix),
        },
      }
    },

    async configResolved(cfg) {
      resolvedViteConfig = cfg
      const root = cfg.root

      // Resolve config file path
      const candidate = resolve(root, configFile)
      if (existsSync(candidate)) {
        configFilePath = candidate
      } else {
        // Try common extensions
        for (const ext of ['.ts', '.mts', '.js', '.mjs']) {
          const alt = resolve(root, configFile.replace(/\.[^.]+$/, '') + ext)
          if (existsSync(alt)) {
            configFilePath = alt
            break
          }
        }
      }

      // Load initial config
      baseConfig = configFilePath ? await loadConfigFile(configFilePath) : {}

      if (generateTypes && configFilePath) {
        generateTypeFile(baseConfig, configFilePath)
      }
    },

    // ── virtual module: virtual:runtime-config ────────────────────────────

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_VIRTUAL_ID
    },

    async load(id, opts) {
      if (id !== RESOLVED_VIRTUAL_ID) return

      const config = await loadAndApply()

      if (opts?.ssr) {
        // Server: export full config (public + private)
        return `const config = ${JSON.stringify(config)};\nexport default config;\n`
      } else {
        // Client: export only public config — matches window.__RUNTIME_CONFIG__
        return (
          `const config = ${JSON.stringify({ public: config.public ?? {} })};\nexport default config;\n`
        )
      }
    },

    // ── SPA: inject public config into HTML ───────────────────────────────

    async transformIndexHtml(html) {
      // In SSR mode the app injects the script itself via RuntimeConfigScript.
      // In SPA / dev mode we inject here so the script is always present.
      if (resolvedViteConfig?.build?.ssr) return html

      const config = await loadAndApply()
      const script = buildConfigScript(config)

      return html.replace(/<head([^>]*)>/, `<head$1>\n    ${script}`)
    },

    // ── HMR: reload virtual module on config file change ─────────────────

    configureServer(server) {
      devServer = server
    },

    async handleHotUpdate({ file }) {
      if (file !== configFilePath) return

      // Reload base config
      baseConfig = await loadConfigFile(file)

      if (generateTypes && configFilePath) {
        generateTypeFile(baseConfig, configFilePath)
      }

      // Invalidate the virtual module so the next import gets fresh data
      const mod = devServer?.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID)
      if (mod) {
        devServer?.moduleGraph.invalidateModule(mod)
        devServer?.ws.send({ type: 'full-reload' })
      }
    },
  }
}
