import type { Plugin, ResolvedConfig } from 'vite'
import { writeFileSync } from 'fs'
import { resolve, relative } from 'path'
import { applyEnvOverrides, buildConfigScript } from '@yanuaraditia/config-core'
import type { RuntimeConfigInput } from '@yanuaraditia/config-core'

const VIRTUAL_ID = '#runtime-config'
const RESOLVED_VIRTUAL_ID = '\0' + VIRTUAL_ID

export interface RuntimeConfigPluginOptions {
  /**
   * Your runtime config object — defined inline, no separate file needed.
   * Use `process.env` to read environment variables at build/dev-server start time.
   *
   * @example
   * runtimeConfigPlugin({
   *   config: {
   *     dbUrl: process.env.DATABASE_URL ?? "",
   *     public: { appVersion: "1.0.0" },
   *   },
   * })
   */
  config?: RuntimeConfigInput

  /**
   * Environment variable prefix used for runtime overrides.
   *
   * Convention (mirrors Nuxt):
   *   {PREFIX}PUBLIC_{KEY}  →  config.public.key
   *   {PREFIX}{KEY}         →  config.key  (private / server-only)
   *
   * @default 'RUNTIME_'
   */
  envPrefix?: string

  /**
   * When true, writes a `runtime-config.d.ts` to your project root
   * with typed module augmentation for useRuntimeConfig().
   * @default false
   */
  generateTypes?: boolean
}

function generateTypeFile(config: RuntimeConfigInput, root: string): void {
  const outPath = resolve(root, 'runtime-config.d.ts')

  const privateKeys = Object.entries(config)
    .filter(([k]) => k !== 'public')
    .map(([k, v]) => `    ${k}: ${JSON.stringify(v) === 'null' ? 'null' : typeof v}`)
    .join('\n')

  const publicObj = (config.public ?? {}) as Record<string, unknown>
  const publicKeys = Object.entries(publicObj)
    .map(([k, v]) => `    ${k}: ${JSON.stringify(v) === 'null' ? 'null' : typeof v}`)
    .join('\n')

  const content = `// Auto-generated by @yanuaraditia/config-vite — do not edit manually.
// Re-run your dev server or build to refresh this file.

declare module '@yanuaraditia/config' {
  interface PrivateRuntimeConfig {
${privateKeys}
  }

  interface PublicRuntimeConfig {
${publicKeys}
  }
}

declare module '#runtime-config' {
  import type { RuntimeConfig } from '@yanuaraditia/config-core'
  const config: RuntimeConfig
  export default config
}

export {}
`
  writeFileSync(outPath, content, 'utf-8')
  console.info(`[runtime-config] Types written to ${relative(process.cwd(), outPath)}`)
}

export function runtimeConfigPlugin(options: RuntimeConfigPluginOptions = {}): Plugin {
  const { config: baseConfig = {}, envPrefix = 'RUNTIME_', generateTypes = false } = options

  let resolvedViteConfig: ResolvedConfig

  function getConfig(): RuntimeConfigInput {
    return applyEnvOverrides(baseConfig, process.env as Record<string, string | undefined>, envPrefix)
  }

  return {
    name: 'runtime-config',
    enforce: 'pre',

    config() {
      return {
        define: {
          __RUNTIME_CONFIG_PREFIX__: JSON.stringify(envPrefix),
        },
      }
    },

    configResolved(cfg) {
      resolvedViteConfig = cfg
      if (generateTypes) {
        generateTypeFile(baseConfig, cfg.root)
      }
    },

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_VIRTUAL_ID
    },

    load(id, opts) {
      if (id !== RESOLVED_VIRTUAL_ID) return

      const config = getConfig()

      if (opts?.ssr) {
        return `const config = ${JSON.stringify(config)};\nexport default config;\n`
      }
      return `const config = ${JSON.stringify({ public: config.public ?? {} })};\nexport default config;\n`
    },

    transformIndexHtml(html) {
      if (resolvedViteConfig?.build?.ssr) return html

      const config = getConfig()
      const script = buildConfigScript(config)
      return html.replace(/<head([^>]*)>/, `<head$1>\n    ${script}`)
    },
  }
}
